### ISSUE TITLE
Transaction in base64

### ISSUE THREAD

**Issue by Imdavyking** [mofalabs/mofa#4]
transaction in sui is not in a way that can be seen from the block explorer
6aERAZE2uC5rPcM5Ei8Xrm3Fgg8nhLKLDmgT1izn3KKg

but got AOOsIoaPsbb4Us/s0OHVw3sCzr9ttkAgXaw044aSc+R37j9e+l9ap4wOVlVLVHeO8VVGr18qY6V8xRM2yEP9JgMPctIyFqzrtWpk7GWZpFo0nj80GcBxnOTRDbG/YyE9QQ==

code line
 final waitForLocalExecutionTx = await client.paySui(txn);

return waitForLocalExecutionTx.transaction.txSignatures.first.toString();

**Comment by 0xmove** [comment]
You should use `waitForLocalExecutionTx.digest` for query in block explorer.
